stages:          # List of stages for jobs, and their order of execution
  - build
  - deploy

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - echo "Building the image..."
    - docker build -t demo/front .
    - docker save demo/front -o demo.tar
    - docker rmi demo/front
    # - npm install --registry=https://registry.npmmirror.com
    # - npm run build
  artifacts:
    untracked: true


deploy-job:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  environment: production
  
  script:
    - echo "Deploying the image..."
    - docker container rm -f demo || true  # 如果容器存在，先移除，忽略移除失败的情况
    - docker load -i demo.tar  # 加载本地的 Docker 镜像
    - docker run -d --name demo -p 8081:8081 demo/front # 启动 Docker 容器{APP_SERVER_PWD}" 
    # - npm run serve
  only:
    - main
