variables:
  DOCKER_IMAGE: registry.gitlab.com/211250199/2024seiii-084frontend
  DOCKER_TAG: $CI_COMMIT_REF_NAME

stages:
  - build
  - deploy

build:
  stage: build
  script:
     - echo "Building the image..."
#    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
#    - docker build -t $DOCKER_IMAGE:$DOCKER_TAG .
#    - docker push $DOCKER_IMAGE:$DOCKER_TAG

deploy:
  stage: deploy
#  before_script:
#    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
#    - eval $(ssh-agent -s)
#    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
#    - mkdir -p ~/.ssh
#    - chmod 700 ~/.ssh
#    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
     - echo "Deploying the image..."
#    - ssh $DEPLOY_SERVER_USER@$DEPLOY_SERVER_IP "docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY"
#    - ssh $DEPLOY_SERVER_USER@$DEPLOY_SERVER_IP "docker pull $DOCKER_IMAGE:$DOCKER_TAG"
#    - ssh $DEPLOY_SERVER_USER@$DEPLOY_SERVER_IP "docker stop $(docker ps -q --filter ancestor=$DOCKER_IMAGE) || true"
#    - ssh $DEPLOY_SERVER_USER@$DEPLOY_SERVER_IP "docker run -d -p 8081:8081 $DOCKER_IMAGE:$DOCKER_TAG"
  only:
    - main
